version: '1.0'
type: tool
name: sosrepair
build:
  type: docker
  tag: squareslab/sosrepair:latest
  context: .
  file: Dockerfile
environment:
  PATH: "/opt/sosrepair/bin:${PATH}"
  CPATH: "/opt/sosrepair/include:${CPATH}"
  PYTHONPATH: "/opt/sosrepair/bindings:${PYTHONPATH}"
